version: 2.1

orbs:
  codecov: codecov/codecov@5.0.0

jobs:
  build:
    docker:
      - image: 'cimg/base:2025.06'
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: 'sudo apt-get update && sudo apt-get install -y catch2 cmake clang llvm-dev libclang-dev make python3'
      - run:
          name: Configuring
          command: './configure CC=clang CXX=clang++ --enable-tests --enable-coverage'
      - run:
          name: Building
          command: 'make -j2'
      - run:
          name: Unit Testing
          command: './bin/run_tests.sh'
      - codecov/upload:
          excludes: src/force-cover
