version: 2.1

branches:
  only:
    - master
    - develop
    - /[0-9]+.x/

executors:
  linux: # Docker using the Base Convenience Image
    docker:
      - image: 'cimg/base:2025.06'
  linuxnew: # Docker using the Base Convenience Image
    docker:
      - image: cimg/base:current-24.04
  macos: &macos-executor # macos executor running Xcode
    macos:
      xcode: 16.2.0
  linuxvm: # executor type
    machine:
      image: ubuntu-2404:current

workflows:
  build:
    jobs:
      # Default:
      # - build:
      #     TEST_INSTALL: 0
      #     TEST_EXTERNAL: 0
      #     TEST_SUBPROJECT: 0
      #     TEST_PKGCONFIG: 0
      #     OS: linux
      #     CC: gcc
      #     OOT: 0
      #     RUN_TESTS: 0
      #     THREADING: none
      #     BUILD_CONFIG: auto
      #     PACKAGES: ''
      #     BLIS: download
      #     COMPAT: 0

      - build:
          OOT: 1
          THREADING: pthread
          COMPAT: 1
          RUN_TESTS: 1
          TEST_INSTALL: 1
      - build:
          CC: clang
          THREADING: openmp
          PACKAGES: 'clang libomp-dev'
          TEST_EXTERNAL: 1
          TEST_PKGCONFIG: 1
          TEST_SUBPROJECT: 1
          TEST_INSTALL: 1
      - build:
          OS: macos
          CC: clang
          RUN_TESTS: 1
          #THREADING: dispatch
      - build:
          THREADING: openmp
          BLIS: external
      - build:
          THREADING: openmp
          CC: nvc
          PACKAGES: 'nvhpc-25-7'
      #- build:
      #    THREADING: tbb
      #    PACKAGES: 'libtbb-dev'
      #- build:
      #    THREADING: none

jobs:
  build:
    parameters:
      COMPAT:
        type: integer
        default: 0
      OS:
        type: executor
        default: linux
      CC:
        type: string
        default: gcc
      OOT:
        type: integer
        default: 0
      RUN_TESTS:
        type: integer
        default: 0
      TEST_INSTALL:
        type: integer
        default: 0
      TEST_EXTERNAL:
        type: integer
        default: 0
      TEST_PKGCONFIG:
        type: integer
        default: 0
      TEST_SUBPROJECT:
        type: integer
        default: 0
      THREADING:
        type: string
        default: none
      BUILD_CONFIG:
        type: string
        default: auto
      PACKAGES:
        type: string
        default: ''
      BLIS:
        type: string
        default: download
    executor: << parameters.OS >>
    steps:
      - checkout

      - when:
          condition:
            not:
              equal: [ *macos-executor, << parameters.OS >> ]
          steps:
            - run:
                name: Installing Dependencies
                command: |
                  export CC="<< parameters.CC >>"
                  if [ $CC = nvc ]; then
                    curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
                    echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
                  fi
                  sudo apt-get update -y && sudo NEEDRESTART_MODE=a apt-get install -y catch2 cmake make python3 << parameters.PACKAGES >>

      - when:
          condition:
            equal: [ *macos-executor, << parameters.OS >> ]
          steps:
            - run:
                name: Installing Dependencies
                command:
                  brew install cmake << parameters.PACKAGES >>

      - run:
          name: Configuring, Building, Testing
          command: |
            git submodule update --init --recursive

            export SRC_DIR=$(pwd)
            export CC="<< parameters.CC >>"
            export OOT="<< parameters.OOT >>"
            export BUILD_CONFIG="<< parameters.BUILD_CONFIG >>"
            export THREADING="<< parameters.THREADING >>"
            export RUN_TESTS="<< parameters.RUN_TESTS >>"
            export TEST_INSTALL="<< parameters.TEST_INSTALL >>"
            export TEST_PKGCONFIG="<< parameters.TEST_PKGCONFIG >>"
            export TEST_EXTERNAL="<< parameters.TEST_EXTERNAL >>"
            export TEST_SUBPROJECT="<< parameters.TEST_SUBPROJECT >>"
            export BLIS="<< parameters.BLIS >>"
            export COMPAT="<< parameters.COMPAT >>"

            case $CC in
                gcc) export CXX=g++;;
                clang) export CXX=clang++;;
                nvc)
                    NVARCH=`uname -s`_`uname -m`; export NVARCH
                    NVCOMPILERS=/opt/nvidia/hpc_sdk; export NVCOMPILERS
                    MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/25.7/compilers/man; export MANPATH
                    PATH=$NVCOMPILERS/$NVARCH/25.7/compilers/bin:$PATH; export PATH
                    export CXX=nvc++
                    ;;
            esac

            pwd
            if [ $OOT -eq 1 ]; then mkdir ../oot; cd ../oot; chmod -R a-w $SRC_DIR; fi
            pwd

            BUILD_DIR=$(pwd)

            echo "Configuration:"
            echo "CC                = $CC"
            echo "CXX               = $CXX"
            echo "OOT               = $OOT"
            echo "BUILD_CONFIG      = $BUILD_CONFIG"
            echo "THREADING         = $THREADING"
            echo "RUN_TESTS         = $RUN_TESTS"
            echo "TEST_INSTALL      = $TEST_INSTALL"
            echo "TEST_PKGCONFIG    = $TEST_PKGCONFIG"
            echo "TEST_EXTERNAL     = $TEST_EXTERNAL"
            echo "TEST_SUBPROJECT   = $TEST_SUBPROJECT"
            echo "BLIS              = $BLIS"
            echo "BUILD_DIR         = $BUILD_DIR"
            echo "SRC_DIR           = $SRC_DIR"
            echo "COMPAT            = $COMPAT"

            CONFIG_ARGS="--prefix=$BUILD_DIR/usr --enable-shared --enable-static --enable-threading=$THREADING CC=$CC CXX=$CXX --with-blis-config-family=$BUILD_CONFIG"

            if [ $BLIS = external ]; then
                mkdir ../blis
                cd ../blis
                git init
                git remote add origin git@github.com:flame/blis
                git fetch --depth=1 origin $(cat $SRC_DIR/blis-git-tag)
                git checkout FETCH_HEAD
                ./configure --prefix=$(pwd)/usr --disable-shared --enable-static -t$THREADING auto
                make -j4 install
                CONFIG_ARGS="$CONFIG_ARGS --with-blis-prefix=$(pwd)/usr"
                cd $BUILD_DIR
            fi

            if [ $RUN_TESTS -eq 1 ]; then
                CONFIG_ARGS="$CONFIG_ARGS --enable-tests"
            fi

            if [ $COMPAT -eq 1 ]; then
                CONFIG_ARGS="$CONFIG_ARGS --enable-compat"
            fi

            CONFIGURE="$SRC_DIR/configure $CONFIG_ARGS"
            echo "Running $CONFIGURE"
            $CONFIGURE
            pwd
            ls -l
            $CC --version
            $CC -v

            if [ $BLIS = external ] && [ -f _deps/blis-build/config.mk ]; then
                echo "BLIS was supposed to be external but it was downloaded instead"
                exit 1
            fi

            make V=1 VERBOSE=1 -j4
            make install

            if [ $RUN_TESTS -eq 1 ]; then
                export OMP_NUM_THREADS=2
                bin/test
            fi

            if [ $TEST_INSTALL -eq 1 ]; then
                $CXX -std=c++20 -o test_install $SRC_DIR/test/install/test_install.cxx -I$BUILD_DIR/usr/include -L$BUILD_DIR/usr/lib -ltblis
            fi

            if [ $TEST_EXTERNAL -eq 1 ]; then
                mkdir ../external
                cd ../external
                cp $SRC_DIR/test/install/test_install.cxx .
                cp $SRC_DIR/test/external/CMakeLists.txt .
                CMAKE_PREFIX_PATH=$BUILD_DIR/usr/lib/cmake cmake .
                make
            fi

            if [ $TEST_SUBPROJECT -eq 1 ]; then
                mkdir ../subproject
                cd ../subproject
                cp $SRC_DIR/test/install/test_install.cxx .
                cp $SRC_DIR/test/subproject/CMakeLists.txt .
                cp -R $SRC_DIR tblis
                cmake .
                make
            fi

            if [ $TEST_PKGCONFIG -eq 1 ]; then
                mkdir ../pkgconfig
                cd ../pkgconfig
                cp $SRC_DIR/test/install/test_install.cxx .
                cp $SRC_DIR/test/pkgconfig/Makefile .
                PKG_CONFIG_PATH=$BUILD_DIR/usr/lib/pkgconfig make shared
                rm $BUILD_DIR/usr/lib/libtblis.so*
                PKG_CONFIG_PATH=$BUILD_DIR/usr/lib/pkgconfig make static
            fi


